FROM node:18

WORKDIR /app

# Install dependencies
COPY server/package.json server/package-lock.json ./
RUN npm install

# Copy application (here for docker-layers caching!)
COPY server ./

EXPOSE 8080

CMD ["npm", "run", "start"]
