# Use node to build the frontend
FROM node:18 AS builder

WORKDIR /app

# Install dependencies - middleware container
COPY client/package.json client/package-lock.json ./
RUN npm install

COPY client ./
RUN npm run build

# ------------------------------ #

# Create Nginx Container
FROM nginx:latest
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
